pacman0:
  env_id: PacMan-v0
  replay_memory_size: 100000
  gamma: 0.99
  epsilon_init: 1.0
  eps_end: 0.01
  eps_dec: 0.998 # use values between 0.95 and 0.999
  lr: 0.001
  num_actions: 4
  mini_batch_size: 64
  input_dims: [6, 50, 80]
  replace_target: 100
  learn_step_counter: 0
  n_games: 220
  save_folder: saved_models